[package]
name = "ignore-check"
version = "0.3.1"
edition = "2024"
description = "Check if a path is ignored"
repository = "https://github.com/qtfkwk/ignore-check"
license = "MIT"

[dependencies]
anyhow = "1.0"
ignore = "0.4"
